### ISSUE TITLE
Add citation text to __init__.py

### ISSUE THREAD

**Issue by nicoguaro** [AppliedMechanics-EAFIT/SolidsPy#12]
Following suggestion by [Arfon Smith](https://speakerdeck.com/arfon/how-to-get-and-give-career-credit-for-software) (@arfon) it is recommended to make the citation process as easy as possible.

**Comment by nicoguaro** [comment]
Fixed by 8b1ddaf68ed269a22c8068c844a996d13a0ab604

**Comment by arfon** [comment]
✨
