### ISSUE TITLE
questions about the documentation

### ISSUE THREAD

**Issue by lonelykid** [AppliedMechanics-EAFIT/SolidsPy#19]
Could you explain how to get this structured mesh in gmsh?
![image](https://solidspy.readthedocs.io/en/latest/_images/Guardar_malla.png)

I tried to add some partition and use transfinite algorithm. The mesh I got was
![image](https://user-images.githubusercontent.com/2936633/54886353-831aaf80-4e5d-11e9-8976-bd5d26d2dbd9.png)

**Comment by nicoguaro** [comment]
This mesh was not generated using a structured algorithm. It is just the default for the ``.geo`` file shown in [the tutorial](https://github.com/AppliedMechanics-EAFIT/SolidsPy/blob/master/docs/tutorials/brazilian_test.rst).

If you want a structured mesh you could make a square close to the center of the circumference, split the arc in two, and add a line at 45 degrees. Check [this example](https://scicomp.stackexchange.com/a/29527/9667).
