### ISSUE TITLE
The following kwargs were not used by contour: 'shading'

### ISSUE THREAD

**Issue by ErosHXL** [AppliedMechanics-EAFIT/SolidsPy#20]
i followed steps of SolidsPy/docs/tutorials/square_example.rst
then 
Number of nodes: 9
Number of elements: 4
Number of equations: 14
Duration for system solution: 0:00:00.007979

Warning (from warnings module):
  File "C:\Users\丁\AppData\Local\Programs\Python\Python37\lib\site-packages\solidspy\postprocesor.py", line 108
    disp_plot(tri, field, levels, shading="gouraud")
UserWarning: The following kwargs were not used by contour: 'shading'

Analysis terminated successfully!

did i do something wrong - -?or lack of mods?

**Comment by nicoguaro** [comment]
Did you manage to see the contour plots?

This is just a warning. There are two options to visualize the results by default: contours and pcolormesh (that is a smooth). The latter has different options and one is `shading=gouraud`. Just ignore that warning without worries.

**Comment by ErosHXL** [comment]
yeah,i want a contour plots,it did't pop up T T.

**Comment by ErosHXL** [comment]
> Did you manage to see the contour plots?
> 
> This is just a warning. There are two options to visualize the results by default: contours and pcolormesh (that is a smooth). The latter has different options and one is `shading=gouraud`. Just ignore that warning without worries.

yeah,i want a contour plots,it did't pop up T T.

**Comment by nicoguaro** [comment]
If you are using Spyder the "pop up" depends on your local configuration. Go to Tool >> Preferences >> IPython console >> Graphics and change "Inline" to another, for example, "Automatic"

**Comment by ErosHXL** [comment]
yes it is.thx bro!!!
