### ISSUE TITLE
TypeError in brazilian_test

### ISSUE THREAD

**Issue by xuzhiping** [AppliedMechanics-EAFIT/SolidsPy#31]
I am experiencing a problem while generating solidspy input files from the gmsh output (*.msh)

https://solidspy.readthedocs.io/en/latest/tutorials/brazilian_test.html

An error was reported as

Traceback (most recent call last):
  File "gen.py", line 11, in <module>
    eles = cells["triangle"]
TypeError: list indices must be integers or slices, not str

Could you help me to solve this issue? Thanks.

**Comment by nicoguaro** [comment]
@xuzhiping, I think that the problem is the version of meshio being used. The tutorial was planned with version 3.0 in mind. Try the following

    pip install meshio==3.0

And let me know if it works.

**Comment by nicoguaro** [comment]
Fixed in version 1.0.12
