### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'int'

### ISSUE THREAD

**Issue by spectereye** [AppliedMechanics-EAFIT/SolidsPy#34]
Hi, `pip install solidpy` then run the demo in README get error below:
```
AttributeError: module 'numpy' has no attribute 'int'.
AttributeError: module 'numpy' has no attribute 'float'
```

**Comment by nicoguaro** [comment]
Resolved in https://github.com/AppliedMechanics-EAFIT/SolidsPy/commit/aca587c5d3f492ad8e36dbc7dd26128e67875a6d.
