### ISSUE TITLE
Generate docs using Sphinx

### ISSUE THREAD

**Issue by nicoguaro** [AppliedMechanics-EAFIT/SolidsPy#5]
Use Sphinx to automatically generate the docs.

**Comment by liubailong-IFS** [comment]
This is a great software, but I have question about how to show the stress and strain, I know the plot.show() can give the result of displacement.

**Comment by nicoguaro** [comment]
@liubailong-IFS, if you change this line ``disp = solids_GUI()`` for ``disps, strains, stresses = solids_GUI(compute_strains=True)`` you would get stresses.

**Comment by liubailong-IFS** [comment]
Thanks, you are so nice. I have try as you told, yes it works.

**Comment by liubailong-IFS** [comment]
Dear nicoguaro
when I run this program, it will give a warning, do you know how to deal with it ? thanks for your help
Warning (from warnings module):
  File "C:\Users\AppData\Local\Programs\Python\Python36-32\lib\site-packages\matplotlib\contour.py", line 967
    s)
UserWarning: The following kwargs were not used by contour: 'shading'

**Comment by nicoguaro** [comment]
Solved by [2f50cb3](https://github.com/AppliedMechanics-EAFIT/SolidsPy/commit/2f50cb3845b377a17220422850801fcca1b69f4e).

**Comment by nicoguaro** [comment]
Solved by [2f50cb3](https://github.com/AppliedMechanics-EAFIT/SolidsPy/commit/2f50cb3845b377a17220422850801fcca1b69f4e).
