### ISSUE TITLE
The unit of calculation

### ISSUE THREAD

**Issue by liubailong-IFS** [AppliedMechanics-EAFIT/SolidsPy#9]
There  four files when calculation
(1)Node(2) Matter(3) Loads(4)eles
can you give me a example that can know the input data unit like“m” 'Pa"
and output data unit
Thanks

**Comment by nicoguaro** [comment]
@liubailong-IFS, you can use several sets of units. Although, that is not clear in the documentation.

Should a table like the following be included in the docs?

![screenshot from 2018-04-16 17-44-56](https://user-images.githubusercontent.com/1097787/38838895-f355f1d8-419d-11e8-9c56-da5255d10396.png)
